# See comment in ./Makefile.base-vars

# Grouping targets
all: html html-chunk pdf ps epub
all-html: html html-chunk
install: install-html install-html-chunk install-pdf install-ps

# Build targets
$(VERSION_SOURCE): version
version:
	@if $(SVNVERSION) . > /dev/null; then \
	  echo '<!ENTITY svn.version "$(L10N_REVISION) '`$(SVNVERSION) .`'">' \
	    > $(VERSION_SOURCE).tmp; \
	else \
	  echo '<!ENTITY svn.version "">' > $(VERSION_SOURCE).tmp; \
	fi
	@if cmp -s $(VERSION_SOURCE) $(VERSION_SOURCE).tmp; then \
	  rm $(VERSION_SOURCE).tmp; \
	else \
	  mv $(VERSION_SOURCE).tmp $(VERSION_SOURCE); \
	fi

epub: $(EPUB_TARGET)

$(EPUB_TARGET): $(EPUB_CHUNK_DIR)
	cd $(EPUB_CHUNK_DIR) && \
	echo "application/epub+zip" > mimetype && \
	zip -0Xq  $(OUTNAME).epub mimetype && \
	zip -Xr9D ../$(OUTNAME).epub *

$(EPUB_CHUNK_DIR): $(ALL_SOURCE) $(VERSION_SOURCE) $(STYLESHEET) $(IMAGES)
	$(ENSURE_XSL)
	$(XSLTPROC) $(HTML_XSLTPROC_OPTS) --output $(EPUB_CHUNK_DIR)/ \
	  $(TOOLS_DIR)/xsl/epub/docbook.xsl $(XML_SOURCE)

html: $(HTML_TARGET)
$(HTML_TARGET): $(ALL_SOURCE) $(VERSION_SOURCE) $(STYLESHEET) $(IMAGES)
	$(ENSURE_XSL)
	$(XSLTPROC) $(HTML_XSLTPROC_OPTS) --output $(HTML_TARGET) \
	  $(TOOLS_DIR)/html-stylesheet.xsl $(XML_SOURCE)

# The trailing slash on the xsltproc --output option is essential to
# output pages into the directory
html-chunk: $(HTML_CHUNK_TARGET)
$(HTML_CHUNK_TARGET): $(ALL_SOURCE) $(VERSION_SOURCE) $(STYLESHEET) $(IMAGES)
	mkdir -p $(HTML_CHUNK_DIR)
	$(IFIMAGES) mkdir -p $(HTML_CHUNK_DIR)/images $(ENDIF)
	$(ENSURE_XSL)
	$(XSLTPROC) $(HTML_XSLTPROC_OPTS) \
           --output $(HTML_CHUNK_DIR)/ \
	   $(TOOLS_DIR)/chunk-stylesheet.xsl $(XML_SOURCE)
	cp $(STYLESHEET) $(HTML_CHUNK_DIR)
	$(IFIMAGES) cp $(IMAGES) $(HTML_CHUNK_DIR)/images $(ENDIF)

fo-a4: $(FO_A4_TARGET)
$(FO_A4_TARGET): $(ALL_SOURCE) $(VERSION_SOURCE) $(IMAGES)
	$(ENSURE_XSL)
	$(XSLTPROC) $(FO_XSLTPROC_OPTS) --output $(FO_A4_TARGET) \
	  $(TOOLS_DIR)/fo-stylesheet-a4.xsl $(XML_SOURCE)

pdf-a4: $(PDF_A4_TARGET)
$(PDF_A4_TARGET): $(FO_A4_TARGET) $(IMAGES)
	$(TOOLS_DIR)/bin/run-fop.sh -fo $(FO_A4_TARGET) -pdf $(PDF_A4_TARGET)

fo-b5: $(FO_B5_TARGET)
$(FO_B5_TARGET): $(ALL_SOURCE) $(VERSION_SOURCE) $(IMAGES)
	$(ENSURE_XSL)
	$(XSLTPROC) $(FO_XSLTPROC_OPTS) --output $(FO_B5_TARGET) \
	  $(TOOLS_DIR)/fo-stylesheet-b5.xsl $(XML_SOURCE)

pdf-b5: $(PDF_B5_TARGET)
$(PDF_B5_TARGET): $(FO_B5_TARGET) $(IMAGES)
	$(TOOLS_DIR)/bin/run-fop.sh -fo $(FO_B5_TARGET) -pdf $(PDF_B5_TARGET)

fo-c5: $(FO_C5_TARGET)
$(FO_C5_TARGET): $(ALL_SOURCE) $(VERSION_SOURCE) $(IMAGES)
	$(ENSURE_XSL)
	$(XSLTPROC) $(FO_XSLTPROC_OPTS) --output $(FO_C5_TARGET) \
	  $(TOOLS_DIR)/fo-stylesheet-c5.xsl $(XML_SOURCE)

pdf-c5: $(PDF_C5_TARGET)
$(PDF_C5_TARGET): $(FO_C5_TARGET) $(IMAGES)
	$(TOOLS_DIR)/bin/run-fop.sh -fo $(FO_C5_TARGET) -pdf $(PDF_C5_TARGET)

fo-letter: $(FO_LETTER_TARGET)
$(FO_LETTER_TARGET): $(ALL_SOURCE) $(VERSION_SOURCE) $(IMAGES)
	$(ENSURE_XSL)
	$(XSLTPROC) $(FO_XSLTPROC_OPTS) --output $(FO_LETTER_TARGET) \
	  $(TOOLS_DIR)/fo-stylesheet-letter.xsl $(XML_SOURCE)

pdf-letter: $(PDF_LETTER_TARGET)
$(PDF_LETTER_TARGET): $(FO_LETTER_TARGET) $(IMAGES)
	$(TOOLS_DIR)/bin/run-fop.sh -fo $(FO_LETTER_TARGET) -pdf $(PDF_LETTER_TARGET)

pdf: pdf-a4 pdf-b5 pdf-c5 pdf-letter

ps-a4: $(PS_A4_TARGET)
$(PS_A4_TARGET): $(FO_A4_TARGET) $(IMAGES)
	$(TOOLS_DIR)/bin/run-fop.sh -fo $(FO_A4_TARGET) -ps $(PS_A4_TARGET)

ps-b5: $(PS_B5_TARGET)
$(PS_B5_TARGET): $(FO_B5_TARGET) $(IMAGES)
	$(TOOLS_DIR)/bin/run-fop.sh -fo $(FO_B5_TARGET) -ps $(PS_B5_TARGET)

ps-c5: $(PS_C5_TARGET)
$(PS_C5_TARGET): $(FO_C5_TARGET) $(IMAGES)
	$(TOOLS_DIR)/bin/run-fop.sh -fo $(FO_C5_TARGET) -ps $(PS_C5_TARGET)

ps-letter: $(PS_LETTER_TARGET)
$(PS_LETTER_TARGET): $(FO_LETTER_TARGET) $(IMAGES)
	$(TOOLS_DIR)/bin/run-fop.sh -fo $(FO_LETTER_TARGET) -ps $(PS_LETTER_TARGET)

ps: ps-a4 ps-b5 ps-c5 ps-letter

# Install targets
$(INSTALL_SUBDIR):
	$(INSTALL) -d $(INSTALL_SUBDIR)

install-html: $(HTML_TARGET) $(INSTALL_SUBDIR)
	$(IFIMAGES) $(INSTALL) -d $(INSTALL_SUBDIR)/images $(ENDIF)
	$(INSTALL) $(HTML_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(STYLESHEET) $(INSTALL_SUBDIR)
	$(IFIMAGES) $(INSTALL) $(IMAGES) $(INSTALL_SUBDIR)/images $(ENDIF)

install-html-chunk: $(HTML_CHUNK_TARGET) $(INSTALL_SUBDIR)
	$(IFIMAGES) $(INSTALL) -d $(INSTALL_SUBDIR)/images $(ENDIF)
	$(INSTALL) $(HTML_CHUNK_DIR)/*.html $(INSTALL_SUBDIR)
	$(INSTALL) $(STYLESHEET) $(INSTALL_SUBDIR)
	$(IFIMAGES) $(INSTALL) $(IMAGES) $(INSTALL_SUBDIR)/images $(ENDIF)

install-pdf: $(PDF_A4_TARGET) $(PDF_B5_TARGET) $(PDF_C5_TARGET) $(PDF_LETTER_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(PDF_A4_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(PDF_B5_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(PDF_C5_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(PDF_LETTER_TARGET) $(INSTALL_SUBDIR)

install-ps: $(PS_A4_TARGET) $(PS_B5_TARGET) $(PS_LETTER_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(PS_A4_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(PS_B5_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(PS_C5_TARGET) $(INSTALL_SUBDIR)
	$(INSTALL) $(PS_LETTER_TARGET) $(INSTALL_SUBDIR)

# Clean targets
clean:
	rm -f $(VERSION_SOURCE)
	rm -f $(HTML_TARGET)
	rm -rf $(HTML_CHUNK_DIR)
	rm -f $(FO_A4_TARGET) $(FO_B5_TARGET) $(FO_C5_TARGET) $(FO_LETTER_TARGET)
	rm -f $(PDF_A4_TARGET) $(PDF_B5_TARGET) $(PDF_C5_TARGET) $(PDF_LETTER_TARGET)
	rm -f $(PS_A4_TARGET) $(PS_B5_TARGET) $(PS_C5_TARGET) $(PS_LETTER_TARGET)

# Utility targets
valid: $(VERSION_SOURCE)
	$(XMLLINT) --noout --nonet --valid $(XML_SOURCE)

